pcengines/apu2-documentation

- docs/firmware_flashing.md
25: 'taget' should be 'target'
> Spelling error in firmware_flashing.md

- ipxe/menu.ipxe
> ipxe: change to autoboot only from net0

- CHANGELOG.md
> changelog: update for v4.0.5

- default.xml
> manifest: update to recent repository changes

- scripts/apu2_fw_rel.sh
> scripts/apu2_fw_rel: udpate to current sources

- docs/building_firmware.md
> docs: update building_firmware.md with instructions for coreboot-4.5.x

- docs/research/apu_bios_write_protect.md
> research: bios write protect

- docs/debug/freeDOS_problems.md
> debug: add note about freeDOS

- docs/debug/mpcie2.md
> docs/debug: add notes about issue with mPcie2 and ASM1062

- docs/AGESA.md
File contains logs from agesa tests
> AGESA tests logs

- docs/debug/mpcie1_mpcie2_ethernet_card.md
Report from debugging APU2 with mPCIe Ethernet Card.
> mpcie1_mpcie2_ethernet_card.md: mPCIe debugging report

- docs/building_env.md
> docs/building_env.md: fix container name

- README.md
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
> README.md: add links to binary releases

- docs/os-status.md
> fix broken links

- docs/release-notes.md
> docs/release-notes.md: change order of releases

- CHANGELOG.md
> CHANGELOG: fix links to CHANGELOGs

- docs/os-status.md
> docs/os-status.md: update pfSense status

- docs/debug/usb-sticks.md
- docs/debug/usb-tests.md
> docs/debug/usb: add test results for new sticks

- docs/apu2_vs_apu4.md
I found this on my disk :)
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
> apu2_vs_apu4: initial commit

- README.md
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
> README.md: versioning scheme change

- docs/pfSense-install-guide.md
> Update to correct dd command

- README.md
- docs/release_process.md
> release_process.md: v4.6.10 is now the earliest supported 4.6.x version

- docs/debug/tpm.md
> docs/debug/tpm.md: add TPM investigation in SeaBIOS

- docs/serial_console.md
> docs/serial_console.md: add guide how to change serial port

- docs/debug/cpu_frequency.md
> cpu_frequency.md: initial commit

- docs/cold_reset.md
> cold_reset.md: initial commit

- docs/research/ROCA.md
- docs/research/openssl_1_1_0.patch
> ROCA.md: ROCA TPM vulnerability verification and status

- docs/research/fast_boot.md
> docs/research/fast_boot.md: add notes from fast boot development

- README.md
- docs/firmware_flashing.md
> docs/firmware_flashing.md: stress the need for full power cycle

- docs/tpm_menu.md
> docs/tpm_menu.md: add TPM menu description

- docs/debug/cpu_frequency.md
> cpu_frequency.md: voltage regulator and community logs

- docs/research/USB_compliance_test.md
Signed-off-by: Piotr Kleinschmidt <piotr.kleinschmidt@3mdeb.com>
> USB compliance tests research

- docs/apu2_vboot.md
5th point - minor change
cp $PWD/release/coreboot/configs.pcengines_apu2_vboot $PWD/release/coreboot/.config ->
cp $PWD/release/coreboot/configs/config.pcengines_apu2_vboot $PWD/release/coreboot/.config
> Update apu2_vboot.md - minor correction

- docs/firmware_flashing.md
Signed-off-by: Piotr Kleinschmidt <piotr.kleinschmidt@3mdeb.com>
> docs/firmware_flashing.md: since what version boardmismatch=force

- README.md
- docs/tianocore_build.md
Signed-off-by: Piotr Kleinschmidt <piotr.kleins@gmail.com>
> docs/tianocore_build.md: building and running coreboot with tianocore

- docs/pfsense_installerconfig.md
Signed-off-by: Artur Raglis <artur.raglis@3mdeb.com>
> docs/pfsense_installerconfig.md: update config location

- docs/pfSense-install-guide.md
Updating memstick installer from 2.4.4-RELEASE-p1 to 2.4.4-RELEASE-p3
> Update pfSense installer to 2.4.4-RELEASE-p3

- README.md
- docs/gpios.md
> docs/gpio.md: add GPIO guide

- README.md
- docs/apu_CPU_boost.md
> docs/apu_CPU_boost.md: add notes about CPU boost

- docs/mpcie_modules.md
> docs/mpcie_modules.md: update solution of WLE200NX issues

- docs/APU_mPCIe_capabilities.md
This way one can read all the information on github.
> Make table more readable

- README.md
- docs/gpios.md
Signed-off-by: Piotr Kleinschmidt <piotr.kleins@gmail.com>
> gpios.md: add known issue section - apuled driver conflict

- docs/firmware_flashing.md
Add how to check firmware version, how to install flashrom on FreeBSD
and "known flashrom problems" section.
Signed-off-by: Marek Kasiewicz <marek.kasiewicz@3mdeb.com>
> docs/firmware_flashing.md: extend flashing docs

- scripts/apu_fw_updater_opnsense.sh
> new version v4.12.0.5

- README.md
- docs/runtime-configuration.md
> docs/runtime-configuration.md: add runtime configuration document

- docs/theory-of-operation.md
Signed-off-by: Igor Bagnucki <igor.bagnucki@3mdeb.com>
> theory-of-operation: Add watchdog information

- docs/mpcie_modules.md
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>
> docs/mpcie_modules.md: explain apu3/4 SIM slot order

- docs/pfsense_installerconfig.md
Signed-off-by: Kamil Pokornicki <kamil.pokornicki@3mdeb.com>
> docs/pfsense_installerconfig.md: update file
